### ISSUE TITLE
Heavy purge server cache may not update CSS version tag

### ISSUE THREAD

**Issue by matt-downs** [Naraceaus/cPanel-Filters#1]
Heavy purge server cache does not increment CSS version tag if current theme has not been "saved" in theme editor - it will just fail silently.

eg in this situation:
![image](https://user-images.githubusercontent.com/6867163/37260287-19057868-25dd-11e8-9759-7a272aa9490b.png)

**Comment by Naraceaus** [comment]
This should be fixed with the new version
